version: '2'

exclude_patterns:
  - config/
  - db/migrate/*
  - db/schema.rb
  - db/seeds/*
  - db/seeds/**/*
  - public/

plugins:
  brakeman:
    enabled: true
  flog:
    enabled: true
    config:
      score_threshold: 20.0
  fixme:
    enabled: true
    config:
      strings:
        - FIXME
        - BUG
        - HACK
        - TODO
        - TEMP
