version: '2'

exclude_patterns:
  - 'config/'
  - 'public/'
  - 'db/seeds/articles/'
  - 'db/seeds/episodes/'
  - 'db/seeds/videos/'
  - 'db/seeds/books/'
  - 'db/seeds/redirects/'

plugins:
  brakeman:
    enabled: true
  flog:
    enabled: true
    config:
      score_threshold: 20.0
  fixme:
    enabled: true
    config:
      strings:
        - FIXME
        - BUG
        - HACK
        - TODO
        - TEMP
  markdownlint:
    enabled: true
  scss-lint:
    enabled: true
