require:
  - rubocop-performance
  - rubocop-rspec

inherit_mode:
  merge:
    - Exclude

AllCops:
  Exclude:
    - 'db/**/*'

Layout/AlignHash:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Metrics/AbcSize:
  Max: 57

Metrics/BlockLength:
  Max: 123

Metrics/ClassLength:
  Max: 210

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/LineLength:
  Max: 200

Metrics/MethodLength:
  Max: 28

Metrics/ParameterLists:
  Max: 6

Metrics/PerceivedComplexity:
  Max: 15

RSpec/DescribeClass:
  Exclude:
    - 'spec/system/*'
RSpec/ExampleLength:
  Max: 20

RSpec/MessageSpies:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 10

RSpec/NestedGroups:
  Max: 4

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MethodDefParentheses:
  Enabled: false

Style/MixinUsage:
  Exclude:
    - 'script/*'
