require:
  - rubocop-performance
  - rubocop-rspec

inherit_mode:
  merge:
    - Exclude

AllCops:
  Exclude:
    # - 'db/**/*'
    - 'db/schema.rb'

Style/UnneededPercentQ:
  Exclude:
    - 'db/**/*'

Layout/AlignHash:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Metrics/AbcSize:
  Max: 57

Metrics/BlockLength:
  Max: 123

Metrics/ClassLength:
  Max: 210

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/LineLength:
  Max: 200
  Exclude:
    - 'db/**/*'

Metrics/MethodLength:
  Max: 28
  Exclude:
    - 'db/migrate/*'

Metrics/ParameterLists:
  Max: 6

Metrics/PerceivedComplexity:
  Max: 15

Naming/VariableNumber:
  EnforcedStyle: snake_case

RSpec/DescribeClass:
  Exclude:
    - 'spec/system/*'

RSpec/ExampleLength:
  Max: 20

RSpec/MessageSpies:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 10

Security/Eval:
  Exclude:
    - 'db/seeds.rb'

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses

Style/MixinUsage:
  Exclude:
    - 'script/*'
