require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  Exclude:
    - 'db/schema.rb'

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Layout/LineLength:
  Max: 186
  Exclude:
    - 'db/**/*'

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Metrics/AbcSize:
  Max: 67

Metrics/BlockLength:
  Exclude:
    - 'config/routes.rb'
  Max: 99

Metrics/ClassLength:
  Max: 131

Metrics/CyclomaticComplexity:
  Max: 12

Metrics/MethodLength:
  Max: 27
  Exclude:
    - 'db/migrate/*'

Metrics/ParameterLists:
  Max: 6

Metrics/PerceivedComplexity:
  Max: 14

Naming/VariableNumber:
  EnforcedStyle: snake_case

RSpec/DescribeClass:
  Exclude:
    - 'spec/system/*'

RSpec/ExampleLength:
  Max: 9
  Exclude:
    - 'spec/system/*'

RSpec/MessageSpies:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 5
  Exclude:
    - 'spec/system/*'

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ExponentialNotation:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses

Style/MixinUsage:
  Exclude:
    - 'script/*'

Style/SlicingWithRange:
  Enabled: true
