require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.5

  Exclude:
    - 'db/**/*'
    - 'script/*'
    - 'bin/*'
    - 'log/**/*'
    - 'node_modules/**/*'
    - 'public/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - '.git/**/*'

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Naming/FileName:
  Exclude:
    - 'Gemfile'
    - 'Guardfile'
    - 'Rakefile'

Rails:
  Enabled: true

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/PerceivedComplexity:
  Max: 15

Metrics/ClassLength:
  Max: 210

Metrics/ParameterLists:
  Max: 6

Metrics/LineLength:
  Max: 200

  Exclude:
    - 'app/middlewares/rack/redirect_pairs.rb'

Metrics/MethodLength:
  Max: 40

Metrics/BlockLength:
  Max: 140

  Exclude:
    - 'spec/**/*'

Metrics/AbcSize:
  Max: 65

Style/Documentation:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/MethodDefParentheses:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/NestedParenthesizedCalls:
  Enabled: false

# TEMP: private and def foo() are at the same indentation level
# This should NOT cause an offense but it does. ¯\_(ツ)_/¯
# https://rubocop.readthedocs.io/en/latest/cops_layout/
Layout/IndentationWidth:
  Enabled: false

# README: the `begin` in BadRequestRescue seems to be required
Style/RedundantBegin:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

# TEMP: Nokogiri’s use of `open` from `open-uri` is being
# confused as Kernel#open by Rubocop
Security/Open:
  Enabled: false

RSpec/NestedGroups:
  Max: 4

RSpec/ExampleLength:
  Max: 20

RSpec/MultipleExpectations:
  Max: 10

RSpec/VerifiedDoubles:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - 'spec/system/*'

# TEMP: Rubocop is wrongly marking hashes as not aligned that are in fact aligned
# https://gist.github.com/veganstraightedge/2bfcd5e5eaacda9f0d9120fb2d285878
Layout/AlignHash:
  Enabled: false

Layout/ClosingHeredocIndentation:
  Exclude:
    - 'app/views/articles/index.json.jbuilder'

Layout/IndentHeredoc:
  Exclude:
    - 'app/views/articles/index.json.jbuilder'
