local:
  service: Disk
  root: <%= Rails.root.join 'storage' %>

test:
  service: Disk
  root: <%= Rails.root.join 'tmp', 'storage' %>

amazon:
  service: S3
  access_key_id:     <%= ENV.fetch('HDRIVE_S3_ACCESS_KEY') { 'TODO' } %>
  secret_access_key: <%= ENV.fetch('HDRIVE_S3_SECRET_KEY') { 'TODO' } %>
  bucket:            <%= ENV.fetch('HDRIVE_S3_BUCKET')     { 'TODO' } %>
  region:            <%= ENV.fetch('HDRIVE_S3_REGION')     { 'TODO' } %>

google:
  service: GCS
  credentials:
    type: service_account
    project_id:     <%= JSON.parse(ENV.fetch('HDRIVE_GOOGLE_JSON_KEY') { '{"todo": "TODO"}' } )['project_id'] %>
    private_key_id: <%= JSON.parse(ENV.fetch('HDRIVE_GOOGLE_JSON_KEY') { '{"todo": "TODO"}' } )['private_key_id'] %>
    private_key:    <%= JSON.parse(ENV.fetch('HDRIVE_GOOGLE_JSON_KEY') { '{"todo": "TODO"}' } )['private_key'] %>
    client_email:   <%= JSON.parse(ENV.fetch('HDRIVE_GOOGLE_JSON_KEY') { '{"todo": "TODO"}' } )['client_email'] %>
    client_id:      <%= JSON.parse(ENV.fetch('HDRIVE_GOOGLE_JSON_KEY') { '{"todo": "TODO"}' } )['client_id'] %>
    auth_uri: "https://accounts.google.com/o/oauth2/auth"
    token_uri: "https://accounts.google.com/o/oauth2/token"
    auth_provider_x509_cert_url: "https://www.googleapis.com/oauth2/v1/certs"
    client_x509_cert_url: <%= JSON.parse(ENV.fetch('HDRIVE_GOOGLE_JSON_KEY') { '{"todo": "TODO"}' } )['client_x509_cert_url'] %>
  project: <%= ENV.fetch('HDRIVE_GOOGLE_BUCKET') { 'TODO' } %>
  bucket: <%= ENV.fetch('HDRIVE_GOOGLE_BUCKET')  { 'TODO' } %>

microsoft:
  service: AzureStorage
  storage_account_name: <%= ENV.fetch('HDRIVE_AZURE_STORAGE')     { 'TODO' } %>
  storage_access_key:   <%= ENV.fetch('HDRIVE_AZURE_PRIMARY_KEY') { 'TODO' } %>
  container:            <%= ENV.fetch('HDRIVE_AZURE_CONTAINER')   { 'TODO' } %>

production:
  service: Mirror
  primary: amazon
  mirrors:
    - google
    - microsoft

staging:
  service: Mirror
  primary: amazon
  mirrors:
    - microsoft

# To test mirroring setup from local development,
# Edit development.rb, chaging this:
# config.active_storage.service = :local
# to this:
# config.active_storage.service = :development_mirrors
development_mirrors:
  service: Mirror
  primary: local
  mirrors:
    - amazon
    - google
    - microsoft
