on: [push]

name: Linter, Rubocop

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set up Ruby
        uses: ruby/setup-ruby@master

      - name: Install Ruby gems
        run: |
          gem install rubocop rubocop-performance rubocop-rails --no-document
          # TODO: Uncomment re-add rubocop-rspec when it's compatible with rubocop <= 1.0

      - name: Run Rubocop linter
        run: |
          rubocop
