on: [push]

name: ERB Linter

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set up Ruby
        uses: ruby/setup-ruby@master

      - name: Install Ruby gems
        run: |
          gem install erb_lint --no-document

      - name: Run ERB linter
        run: |
          erblint app
