on: [push]

name: Linter, ERB

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set up Ruby
        uses: ruby/setup-ruby@master

      # TODO: Uncomment when erb_lint is compatible with rubocop <= 1.0
      # - name: Install Ruby gems
      #   run: |
      #     gem install erb_lint --no-document
      #
      # - name: Run ERB linter
      #   run: |
      #     erblint app
