on: [push]

name: Fasterer Linter

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set up Ruby
        uses: ruby/setup-ruby@master

      - name: Install Ruby gems
        run: |
          gem install fasterer --no-document

      - name: Run Fasterer linter
        run: |
          fasterer
