name: Ruby

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: ruby:2.6.5

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      # - name: Test
      #   run: |
      #     bundle install --jobs 4 --retry 3
